import { Solway } from 'next/font/google';
import './globals.css';
import Menu from '@/components/menu';
import Image from 'next/image';
import Header from '@/components/header';
import { ChordsProvider } from '@/context/chords_context';

const solway = Solway({
	variable: '--font-solway',
	subsets: ['latin'],
	weight: '400',
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${solway.variable}  antialiased bg-white max-h-screen`}
			>
				<ChordsProvider>
					<Header></Header>
					{children}
					<footer className="bg-navy h-28 fixed bottom-0 w-screen">
						<Image
							src="/guitar_dojo_logo.png"
							width={175}
							height={100}
							alt="Guitar Dojo Logo"
						></Image>
						<Menu />
					</footer>
				</ChordsProvider>
			</body>
		</html>
	);
}
