import { Solway } from 'next/font/google';
import './globals.css';

const solway = Solway({
	variable: '--font-solway',
	subsets: ['latin'],
	weight: '400',
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${solway.variable}  antialiased bg-white max-h-screen w-screen overflow-hidden`}
			>
				{children}
			</body>
		</html>
	);
}
